# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: get-new-version
      with:
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog@6.0.0
          @semantic-release/git
        branches: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'main',
            'next',
            'next-major',
            {
              name: 'feat/workflow-build',
              prerelease: true
            },
            {
              name: 'beta',
              prerelease: true
            },
            {
              name: 'alpha',
              prerelease: true
            }
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build
      shell: bash
      run: |
        echo "new release version: ${{ steps.get-new-version.outputs.new_release_version }}"
        chmod u+x build.sh
        ./build.sh ${{ steps.get-new-version.outputs.new_release_version }}

    - name: Test
      shell: bash
      run: |
        chmod u+x test.sh
        ./test.sh
